---
- name: install tomcat server
  hosts: webserverstest
  become: true

  tasks:
  - name: install java
    yum:
      name: java
      state: latest
  - name: download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.69/bin/apache-tomcat-9.0.69.tar.gz
      dest: /usr/local
  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.69.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-9.0.69/bin/startup.sh
