apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sample
            image: gcr.io/k8s-minikube/storage-provisioner:v5
            args: ['/bin/sh', '-c', 'date; echo Hello from the Kubernetes cluster']
          restartPolicy: OnFailure



